abbreviation_mapping:
  LIC: "Life Insurance Policy"
  TPA: "Third Party Administrator"
  UIN: "Unique Identification Number"
  IRDA: "Insurance Regulatory and Development Authority"
  NAV: "Net Asset Value"